export const MAX_CANVAS_WIDTH = 2718;
export const DEFAULT_LABEL_SIZE = 18;
export const LINE_ANIMATION_TIME = 1000;
export const CHART_X_LABEL_HEIGHT_RECTIFIER = 2;
export const X_AXIS_LABEL_WIDTH_RECTIFIER = 15;
export const Y_AXIS_LEGEND_TRUE_VALUE = 2.6;
export const Y_AXIS_LEGEND_FALSE_VALUE = 0.5;
export const Y_AXIS_LABEL_HORIZONTAL_GAP = 10;
